#!/bin/bash

# Dependency setup
insert_task_after "01-packages" \
    "$plugindir/instance-store-ami-tasks/01-host_dependencies"

# Additional vars for euca tools that manage bundles
insert_task_after "07-host-information" \
    "$plugindir/instance-store-ami-tasks/08-more-host-info"

# New tasks that bundle our image and upload it to S3
insert_task_after "72-unmount-volume" \
    "$plugindir/instance-store-ami-tasks/72a-create_sparse_file"
insert_task_after "72a-create_sparse_file" \
    "$plugindir/instance-store-ami-tasks/72b-bundle-image"
insert_task_after "72b-bundle-image" \
    "$plugindir/instance-store-ami-tasks/72c-upload-bundle"
insert_task_after "72c-upload-bundle" \
    "$plugindir/instance-store-ami-tasks/72d-delete-bundle-files"
insert_task_after "72d-delete-bundle-files" \
    "$plugindir/instance-store-ami-tasks/72e-delete_sparse_file"

# We don't need to create a volume snapshot for instace-backed AMIs.
remove_task "80-ebs-snapshot"

# Replace ${TASK_CREATE_AMI} as instance-store AMIs are registered
# differently
insert_task_after "${TASK_CREATE_AMI}" \
    "$plugindir/instance-store-ami-tasks/95-register-instance-ami"
remove_task "${TASK_CREATE_AMI}"
TASK_CREATE_AMI="95-register-instance-ami"
