#!/bin/bash
#
# Ensure euca2ools in installed. We use it to communicate with AWS.


declare -i euca2ools_major_ver="$(grep-available -s Version -P euca2ools | \
        sed -e 's/^Version\:\ \(.\).*$/\1/')"


function install_euca2ools
{
	# We want to fail if make fails, so don't start a subshell with ()
	# Remember the old dir
	local orig_pwd=$(pwd)

	cd euca2ools-2.1.3

	python setup.py build | spin
	[ $PIPESTATUS == 0 ] || die "euca2ools build failed!"

	python setup.py install | spin
	[ $PIPESTATUS == 0 ] || die "euca2ools installation failed!"

	cd $orig_pwd
}


# Check if we already have the version we need in the repos.
if [ "${euca2ools_major_ver}" -ge 2 ]
then
	# If we don't have the euca2ools package already installed
	if ! grep-status -s Status -P euca2ools | grep -q 'installed$'
	then
		# Note that host_packages have already been installed at this
		# point, so we need to manually install it here.
		apt-get -f install euca2ools | spin
		[ $PIPESTATUS == 0 ] || die "Installing host packages failed!"
	fi
else
	if [ ! -d $scriptdir/euca2ools ]
	then
		wget -qO $scriptdir/euca2ools-2.1.3.tar.gz \
			https://github.com/eucalyptus/euca2ools/archive/2.1.3.tar.gz
		tar zxf $scriptdir/euca2ools-2.1.3.tar.gz
	fi

	# make the euca2ools if they are not installed or the version is wrong
	if ! command -v euca-version > /dev/null 2>&1; then
		install_euca2ools
	elif [[ ! "`euca-version`" =~ euca2ools\ 2.1.* ]]; then
		install_euca2ools
	fi
fi
