#!/bin/bash
# Register the uploaded bundle as a new AMI

# Figure out which pvGrub kernel ID we need
# See https://wiki.debian.org/Cloud/AmazonEC2Image/Wheezy
case $region in
        us-east-1)
                [ $arch = 'amd64' ] && aki="aki-655a600c"
                [ $arch = 'i386' ] && aki="aki-b6aa75df"
        ;;
        us-west-1)
                [ $arch = 'amd64' ] && aki="aki-46c7fa03"
                [ $arch = 'i386' ] && aki="aki-f57e26b0"
        ;;
        us-west-2)
                [ $arch = 'amd64' ] && aki="aki-68026058"
                [ $arch = 'i386' ] && aki="aki-fa37baca"
        ;;
        eu-west-1)
                [ $arch = 'amd64' ] && aki="aki-80d322f7"
                [ $arch = 'i386' ] && aki="aki-75665e01"
        ;;
        ap-southeast-1)
                [ $arch = 'amd64' ] && aki="aki-34aafc66"
                [ $arch = 'i386' ] && aki="aki-f81354aa"
        ;;
        ap-southeast-2)
                [ $arch = 'amd64' ] && aki="aki-3d3aa407"
                [ $arch = 'i386' ] && aki="aki-33990e09"
        ;;
        ap-northeast-1)
                [ $arch = 'amd64' ] && aki="aki-f780eaf6"
                [ $arch = 'i386' ] && aki="aki-42992843"
        ;;
        sa-east-1)
                [ $arch = 'amd64' ] && aki="aki-771bbb6a"
                [ $arch = 'i386' ] && aki="aki-ca8f51d7"
        ;;
        us-gov-west-1)
                [ $arch = 'amd64' ] && aki="aki-79a4c05a"
                [ $arch = 'i386' ] && aki="aki-7ba4c058"
        ;;
        *) die "Unrecognized region:" "$region"
esac


[ $arch = 'i386' ] && ami_arch='i386'
[ $arch = 'amd64' ] && ami_arch='x86_64'

log "Registering an AMI"
ami_id=`euca-register \
        "${S3_BUCKET}/${ami_name}.manifest.xml" \
        --name "$ami_name" --description "$description" \
        --architecture "$ami_arch" --kernel "$aki" \
        | awk '{print $2}'`

# If the user has already created an unnamed AMI today,
# this will fail, so give the AMI registration command to the user
if [[ ! "$ami_id" =~ ^ami-[0-9a-z]{8}$ ]]; then
        die \
                "Unable to register an AMI." \
                "You can do it manually with:" \
                "`which euca-register` \\\\" \
                "'${S3_BUCKET}/${ami_name}.manifest.xml' \\\\" \
                "--name '$ami_name' --description '$description' \\\\" \
                "--architecture '$ami_arch' --kernel '$aki'"
fi
log "Your AMI has been created with the ID '$ami_id'"

